<?php
$op            = (empty($_GET['op'])?"":$_GET['op']);
$op            = (empty($_POST['op'])?$op:$_POST['op']);
$list_id       = (empty($_GET['list_id'])?"":$_GET['list_id']);
$list_id       = (empty($_POST['list_id'])?$list_id:$_POST['list_id']);
$action        = (empty($_GET['action'])?"":$_GET['action']);
$action        = (empty($_POST['action'])?$action:$_POST['action']);
$page          = (empty($_GET['page'])?"listes":$_GET['page']);
$page          = (empty($_POST['page'])?$page:$_POST['page']);
$data          = (empty($_GET['data'])?"ch":$_GET['data']);
$id_mailq      = (empty($_GET['id_mailq'])?"":$_GET['id_mailq']);
$l             = (empty($_GET['l'])?"l":$_GET['l']);
$t             = (empty($_GET['t'])?"":$_GET['t']);
$tm            = (empty($_GET['tm'])?"":$_GET['tm']);
$t             = (empty($_POST['t'])?$t:$_POST['t']);
$startprofils  = (empty($_GET['st'])?1:$_GET['st']);
$startprofils  = (empty($_POST['st'])?$startprofils:$_POST['st']);
$limiteprofils = (empty($_GET['li'])?30:$_GET['li']);
$limiteprofils = (empty($_POST['li'])?$limiteprofils:$_POST['li']);
$error_list    = false;
$subscriber_op_msg = '';
$smtp_manage_msg   = '';
$smtp_id       = (empty($_GET['smtp_id'])?'':$_GET['smtp_id']);
$smtp_id       = (empty($_POST['smtp_id'])?$smtp_id:$_POST['smtp_id']);
$ta            = (!empty($_GET['ta'])&&$_GET['ta']=='all'?'all':(int)$list_id);
$array_profils_item = array(15,30,50,100,500,-1);
$itemp         = (int)(!empty($_GET['itemp'])&&in_array($_GET['itemp'], $array_profils_item)?$_GET['itemp']:30);
$array_sort_item = array('alpha','clics','cmpo');
$sort          = (!empty($_GET['sort'])&&in_array($_GET['sort'], $array_sort_item)?$_GET['sort']:'alpha');
$viewms        = (empty($_GET['viewms'])?"list":$_GET['viewms']);
$viewms        = (empty($_POST['viewms'])?$viewms:$_POST['viewms']);
$account       = (empty($_GET['account'])?"":$_GET['account']);
$account       = (empty($_POST['account'])?$account:$_POST['account']);

